namespace Sql_Server_Monitoring.Domain.Models
{
    public enum AlertType
    {
        HighCpu,
        LowMemory,
        IoBottleneck,
        DatabaseConnectivity,
        UnusedIndex,
        MissingIndex,
        FragmentedIndex,
        SlowQuery,
        TempdbContention,
        SecurityVulnerability,
        CorruptionDetected,
        BackupFailure,
        BackupMissing,
        LongRunningQuery,
        Blocking,
        Deadlock,
        LowDiskSpace,
        JobFailure,
        DatabaseMirroringFailure,
        LogShippingFailure,
        AvailabilityGroupFailure,
        IdentityColumnExhaustion,
        SchemaChangeDetected,
        ConfigurationChangeDetected,
        ResourceGovernorChange,
        QueryStoreIssue,
        DbccCheckFailure,
        TraceFlag,
        DriverIssue,
        TempDbFileIssue,
        CustomCheck
    }
}
